export const incidents = [
    {
        id: '3',
        title: 'Samsung not responding',
        description: 'It just stopped working',
        priority: 'Hight',
        category: 'Bug',
        assignee: 'Justin Burger',
        impact: 'Critical',
        resolution: 'Pending',
        timeSpent: 'N/A',
        comments: 'This has been happening for almost a week now, with no long term resolution',
        date: '2023-03-02',
        reporter: 'Malaika James',
        status: 'Pending'
    },
    {
        id: '5124',
        title: 'Sysmtem down',
        description: 'It just stopped working',
        priority: 'Medium',
        category: 'Bug',
        assignee: 'Justin Burger',
        impact: 'Critical',
        resolution: 'Pending',
        timeSpent: 'N/A',
        comments: 'This has been happening for almost a week',
        date: '2023-03-22',
        reporter: 'David Mensah',
        status: 'Resolved'
    },
    {
        id: '5125',
        title: 'Error when logging',
        description: 'It just stopped working',
        priority: 'High',
        category: 'Bug',
        assignee: 'Justin Burger',
        impact: 'Critical',
        resolution: 'Pending',
        timeSpent: 'N/A',
        comments: 'This has been happening for almost a week now, with no long term resolution',
        date: '2023-03-15',
        reporter: 'Simon Dhlomo',
        status: 'In Progress'
    },
    {
        id: '5126',
        title: 'Forgot password',
        description: 'It just stopped working',
        priority: 'Low',
        category: 'Bug',
        assignee: 'Justin Burger',
        impact: 'Critical',
        resolution: 'Pending',
        timeSpent: 'N/A',
        comments: 'This has been happening for almost a week now, with no long term resolution',
        date: '2023-02-25',
        reporter: 'Zimbini Msomi',
        status: 'Pending'
    },
    {
        id: '5127',
        title: 'Access Denied',
        description: 'It just stopped working',
        priority: 'High',
        category: 'Bug',
        assignee: 'Justin Burger',
        impact: 'Critical',
        resolution: 'Pending',
        timeSpent: 'N/A',
        comments: 'This has been happening for almost a week now, with no long term resolution',
        date: '2023-03-11',
        reporter: 'Jacob Dolly',
        status: 'Pending'
    }
]